[phases.setup]
nixPkgs = [
    "tesseract",
    "pkg-config",
    "gcc",
    "cmake",
    "opencv4",
    "glib",
    "zlib",
    "libpng",
    "libjpeg",
    "libwebp",
    "libtiff",
    "libGL",
    "libGLU",
    "xorg.libX11",
    "xorg.libXext",
    "postgresql"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]
