"""
=============================================================================
ALEMBIC MIGRATIONS - Database Schema Management
=============================================================================

This directory contains Alembic database migration scripts for the
Receipt Extractor platform.

Setup:
    1. Initialize Alembic (if not already done):
       alembic init migrations
    
    2. Configure alembic.ini with your database URL
    
    3. Create a new migration:
       alembic revision --autogenerate -m "Description"
    
    4. Apply migrations:
       alembic upgrade head

=============================================================================
"""

# This file marks the migrations directory as a Python package
# Actual migration scripts will be generated by Alembic
